### PR TITLE
add PHP 8.2

### PR DESCRIPTION
**Pull request by macbookandrew**

### CODE REVIEW

**Comment by axllent** [comment]
Thank you @macbookandrew! Would you mind please also updating your PR to include the necessary changes to the CI build script in `.github/workflows/docker-build.yml`? Then I can merge it in complete.

**Comment by macbookandrew** [comment]
🤦🏻 I’m too used to GitLab 😆

**Comment by axllent** [comment]
All good, and thank you! I'll merge this in later today and release a new version.

**Comment by axllent** [comment]
Thanks again, 8.2 has just been deployed to docker hub :+1:

**Pull request merged**
